# Generated by Django 5.2.4 on 2025-07-24 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_learningtopic_skill_learningresource_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockInterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('difficulty_level', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.companydrive')),
            ],
        ),
    ]
